import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {projectCropPoint,unprojectCropPoint,cropImageStyle,fitRect,polylinePath,routeSegments,findScene,transitionKind,resolveProgress} from './story-math.mjs';
const story=JSON.parse(readFileSync(new URL('../data/story.json',import.meta.url)));
const anchors=JSON.parse(readFileSync(new URL('../data/anchors.json',import.meta.url)));
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-9,`${a} != ${b}`);
test('crop origin and endpoint map correctly',()=>{assert.deepEqual(projectCropPoint([300,190],[300,190,1190,830],390,272.0168067),[0,0]); assert.deepEqual(projectCropPoint([1490,1020],[300,190,1190,830],390,273),[390,273]);});
test('projection reverses for all story anchors',()=>{for(const p of Object.values(anchors.points)){let q=projectCropPoint(p,anchors.viewports.mobile,390,390*830/1190);let r=unprojectCropPoint(q,anchors.viewports.mobile,390,390*830/1190);near(r[0],p[0]);near(r[1],p[1]);}});
test('seed home/clinic points survive the proposed mobile crop',()=>{for(const key of ['homeGate','clinicEntrance']){const [x,y]=projectCropPoint(anchors.points[key],anchors.viewports.mobile,390,272.0168067);assert.ok(x>=0&&x<=390&&y>=0&&y<=272.0168067);}});
test('crop style uses the same native image space',()=>{assert.deepEqual(cropImageStyle([0,0,1536,1024]),{width:'100%',height:'100%',left:'0%',top:'0%'});});
test('contain letterboxing and cover crop are explicit',()=>{const a=fitRect(1536,1024,1200,600);near(a.scale,.5859375);near(a.x,150);near(a.y,0);const b=fitRect(1536,1024,1200,600,'cover');near(b.y,-100);near(b.x,0);});
test('invalid geometry is rejected',()=>{assert.throws(()=>projectCropPoint([NaN,1],[0,0,1,1],10,10));assert.throws(()=>cropImageStyle([0,0,0,1]));assert.throws(()=>fitRect(1,1,0,1));assert.throws(()=>fitRect(1,1,1,1,'stretch'));});
test('route splits retain contiguous endpoints',()=>{const s=routeSegments(anchors.route,anchors.affectedSegment.startIndex,anchors.affectedSegment.endIndex);assert.deepEqual(s.before.at(-1),s.affected[0]);assert.deepEqual(s.affected.at(-1),s.after[0]);assert.match(polylinePath(s.affected),/^M /);});
test('invalid route and indices rejected',()=>{assert.throws(()=>polylinePath([[1,2]]));assert.throws(()=>routeSegments([[1,2],[3,4]],1,0));});
test('nine states and four chapters in expected order',()=>{assert.equal(story.scenes.length,9);assert.equal(story.chapters.length,4);assert.equal(findScene(story.scenes,'S3B-OBS').chapter,'03');assert.equal(findScene(story.scenes,'S4-PUBLIC').chapter,'04');assert.throws(()=>findScene(story.scenes,'missing'));});
test('all consequence-to-ending scenes use the same W2',()=>{const start=story.scenes.findIndex(s=>s.id==='S3A-01');assert.ok(story.scenes.slice(start).every(s=>s.waterState==='W2'));});
test('water change differs from overlay change',()=>{assert.equal(transitionKind(story.scenes[1],story.scenes[2]),'fade-through-paper');assert.equal(transitionKind(story.scenes[3],story.scenes[5]),'overlay-only');assert.equal(transitionKind(story.scenes[3],story.scenes[5],true),'instant');assert.equal(transitionKind(story.scenes[1],story.scenes[1]),'none');});
test('progress clamps and spans first/last reading states',()=>{assert.equal(resolveProgress(story.scenes,-1).id,'S1-01');assert.equal(resolveProgress(story.scenes,1).id,'S4-END');assert.equal(resolveProgress(story.scenes,2).id,'S4-END');assert.throws(()=>resolveProgress(story.scenes,NaN));});
