"""Build an honest readiness assessment for the flood-label factory."""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from datetime import datetime, timezone
import hashlib
import json
from pathlib import Path
from typing import Any

import pandas as pd

from floodguard.label_factory.adjudication import (
    AdjudicationError,
    pair_locked_annotations,
)
from floodguard.label_factory.annotations import (
    AnnotationValidationError,
    ReviewStage,
    annotation_content_sha256,
    load_annotation_log,
)
from floodguard.label_factory.calibration import (
    ReviewerCalibrationError,
    load_reviewer_calibration_receipt,
)
from floodguard.label_factory.event_registry import (
    EventRegistryError,
    load_events,
    load_source_assets,
    validate_event_source_registry,
)
from floodguard.label_factory.manifests import (
    ManifestContractError,
    validate_grid_manifests,
)
from floodguard.label_factory.processing_alignment import (
    PROCESSING_ALIGNMENT_RECEIPT_SCHEMA,
    ProcessingAlignmentError,
    ReceiptInput,
    validate_processing_alignment_receipt,
)
from floodguard.label_factory.review_workflow import (
    AGREEMENT_EVIDENCE_SCHEMA,
    ReviewWorkflowError,
    _require_agreement_gates,
    load_json_object,
    load_labelset_validation_receipt,
)
from floodguard.label_factory.rights_clearance import (
    RightsClearanceError,
    validate_rights_clearance_package,
)


GRID_VALIDATION_RECEIPT_SCHEMA = "floodguard.grid_validation_receipt.v3"
GRID_VALIDATOR_ID = (
    "validate_processing_alignment_receipt+validate_grid_manifests@label_factory_v3"
)
GRID_RECEIPT_KEYS: frozenset[str] = frozenset(
    {
        "artifact_schema",
        "validator",
        "validated_at_utc",
        "event_registry_sha256",
        "source_registry_sha256",
        "governance_package_id",
        "governance_package_manifest_sha256",
        "governance_package_seal_sha256",
        "governance_binding_status",
        "production_readiness_eligible",
        "processing_alignment_receipt_schema",
        "processing_alignment_receipt_sha256",
        "tile_manifest_sha256",
        "query_manifest_sha256",
        "supported_query_derivation_sha256",
        "grid_contract_sha256s",
        "event_count",
        "source_asset_count",
        "tile_count",
        "query_count",
        "query_model_only",
        "eligible_for_decision_layer",
        "eligible_for_fpps",
        "eligible_for_warning",
        "receipt_sha256",
    }
)

READINESS_COLUMNS: tuple[str, ...] = (
    "check_id",
    "phase",
    "status",
    "severity",
    "observed",
    "required",
    "blocker",
    "source_timestamp",
    "confidence_class",
    "assumptions",
)


class LabelFactoryReadinessError(ValueError):
    """Raised when label-factory readiness evidence is malformed."""


@dataclass(frozen=True, slots=True)
class _EvidenceAssessment:
    """One fail-closed readiness-evidence result."""

    ready: bool
    observed: str


def build_label_factory_readiness(
    manual_reference_manifest: pd.DataFrame | str | Path,
    weak_feature_manifest: pd.DataFrame | str | Path,
    weak_ml_metrics: pd.DataFrame | str | Path,
    *,
    canonical_tile_manifest: pd.DataFrame | str | Path | None = None,
    canonical_query_manifest: pd.DataFrame | str | Path | None = None,
    event_manifest: pd.DataFrame | str | Path | None = None,
    source_asset_manifest: pd.DataFrame | str | Path | None = None,
    processing_alignment_receipt: ReceiptInput | None = None,
    supported_query_derivation: str | Path | None = None,
    governance_package: str | Path | None = None,
    allow_ungoverned_fixture: bool = False,
    grid_validation_receipt: str | Path | None = None,
    annotation_log: str | Path | None = None,
    agreement_evidence: str | Path | None = None,
    reviewer_calibration_receipt: str | Path | None = None,
    labelset_validation_receipt: str | Path | None = None,
    annotation_manifest: pd.DataFrame | str | Path | None = None,
    labelset_manifest: pd.DataFrame | str | Path | None = None,
) -> pd.DataFrame:
    """Assess engineering, human-review, and promotion gates independently.

    Optional evidence is deliberately fail-closed.  A tile-shaped table, two
    reviewer identifiers, or a compact release-summary CSV cannot satisfy a
    readiness gate.  Canonical-grid readiness requires either all four source
    contracts to pass their production validators or a self-hashed receipt
    generated by :func:`build_grid_validation_receipt`.  Review readiness
    requires a verified annotation hash chain plus agreement evidence bound to
    the exact latest A/B revisions. Reviewer readiness is a separate gate that
    requires a passing self-hashed calibration receipt built on fixed
    ``reviewer_calibration`` queries. Training-label readiness requires the
    self-hashed validation receipt produced by ``review_workflow``.

    ``annotation_manifest`` and ``labelset_manifest`` remain as compatibility
    aliases, but their evidence is subjected to the new strict semantics.  In
    particular, legacy DataFrames/CSVs are rejected and reported as validation
    failures rather than interpreted as proof.
    """

    manual = _coerce_required(manual_reference_manifest, "manual reference manifest")
    features = _coerce_required(weak_feature_manifest, "weak feature manifest")
    metrics = _coerce_required(weak_ml_metrics, "weak ML metrics")
    _require_columns(
        manual,
        (
            "reference_mask_status",
            "feature_count",
            "unqualified_ml_label_allowed",
            "processing_allowed",
            "inspected_at_utc",
        ),
        "manual reference manifest",
    )
    _require_columns(
        features,
        ("sample_pixel_count", "reference_positive_pixel_count", "source_timestamp"),
        "weak feature manifest",
    )
    _require_columns(
        metrics,
        ("can_feed_decision_layer", "ml_area_error_ratio", "confidence_class"),
        "weak ML metrics",
    )
    manual_row = manual.iloc[0]
    feature_row = features.iloc[0]
    metric_row = metrics.iloc[0]
    timestamp = str(feature_row["source_timestamp"] or manual_row["inspected_at_utc"])
    confidence = str(metric_row["confidence_class"] or "low")
    rows: list[dict[str, object]] = []
    rows.append(
        _row(
            "weak_reference_seed_scope",
            "phase_0",
            status="ready_for_seed_only"
            if str(manual_row["reference_mask_status"]) == "weak_reference_candidate"
            else "blocked",
            severity="high",
            observed=(
                f"status={manual_row['reference_mask_status']}; "
                f"features={manual_row['feature_count']}"
            ),
            required="weak positive-unlabeled seed; never complete binary truth",
            blocker=(
                "None for seed selection; official validation and unqualified labels remain blocked."
                if str(manual_row["reference_mask_status"]) == "weak_reference_candidate"
                else "Manual reference is not a recognized weak-reference candidate."
            ),
            timestamp=timestamp,
            confidence=confidence,
        )
    )
    ml_allowed = _truthy(manual_row["unqualified_ml_label_allowed"])
    release_source, release_conflict = _select_aliased_evidence(
        preferred=labelset_validation_receipt,
        legacy=labelset_manifest,
        preferred_name="labelset_validation_receipt",
        legacy_name="labelset_manifest",
    )
    release = (
        _EvidenceAssessment(False, release_conflict)
        if release_conflict
        else _training_release_assessment(release_source)
    )
    rows.append(
        _row(
            "cleared_training_labels",
            "phase_1",
            status="ready" if release.ready else "blocked",
            severity="critical",
            observed=(
                f"legacy_unqualified_ml_label_allowed={ml_allowed}; "
                f"{release.observed}"
            ),
            required="rights-cleared, explicitly reviewed multiclass labels",
            blocker=(
                ""
                if release.ready
                else (
                    "A weak-reference manifest cannot clear training labels, even if a "
                    "legacy flag is relaxed; a verified labelset validation receipt is required."
                )
            ),
            timestamp=timestamp,
            confidence=confidence,
        )
    )
    grid = _canonical_grid_assessment(
        event_manifest=event_manifest,
        source_asset_manifest=source_asset_manifest,
        processing_alignment_receipt=processing_alignment_receipt,
        supported_query_derivation=supported_query_derivation,
        canonical_tile_manifest=canonical_tile_manifest,
        canonical_query_manifest=canonical_query_manifest,
        grid_validation_receipt=grid_validation_receipt,
        governance_package=governance_package,
        allow_ungoverned_fixture=allow_ungoverned_fixture,
    )
    rows.append(
        _row(
            "canonical_projected_grid",
            "phase_1",
            status="ready" if grid.ready else "blocked",
            severity="critical",
            observed=grid.observed,
            required="terrain-corrected projected grid with fixed resolution and stable ids",
            blocker=(
                ""
                if grid.ready
                else (
                    "Build and validate the complete event/source/processing/tile/query "
                    "grid contract "
                    "or supply its verified self-hashed validation receipt."
                )
            ),
            timestamp=timestamp,
            confidence=confidence,
        )
    )
    review_source, review_conflict = _select_aliased_evidence(
        preferred=annotation_log,
        legacy=annotation_manifest,
        preferred_name="annotation_log",
        legacy_name="annotation_manifest",
    )
    review = (
        _EvidenceAssessment(False, review_conflict)
        if review_conflict
        else _double_review_assessment(review_source, agreement_evidence)
    )
    calibration = _reviewer_calibration_assessment(
        reviewer_calibration_receipt
    )
    rows.append(
        _row(
            "reviewer_calibration_complete",
            "phase_1",
            status="ready" if calibration.ready else "blocked",
            severity="critical",
            observed=calibration.observed,
            required=(
                "named formal reviewers pass at least eight fixed calibration "
                "queries before production review"
            ),
            blocker=(
                ""
                if calibration.ready
                else (
                    "Provide a verified passing reviewer-calibration receipt; "
                    "calibration cells remain ineligible for model training."
                )
            ),
            timestamp=timestamp,
            confidence=confidence,
        )
    )
    rows.append(
        _row(
            "blind_double_review",
            "phase_1",
            status="ready" if review.ready else "blocked",
            severity="critical",
            observed=review.observed,
            required="at least two independent blinded reviewers for the formal pilot",
            blocker=(
                ""
                if review.ready
                else (
                    "Human review is incomplete, unpaired, unlocked, not independently "
                    "blinded, or not bound to exact agreement and provenance hashes."
                )
            ),
            timestamp=timestamp,
            confidence=confidence,
        )
    )
    rows.append(
        _row(
            "immutable_training_labelset",
            "phase_1",
            status="ready" if release.ready else "blocked",
            severity="critical",
            observed=release.observed,
            required="QA-passing immutable release with resolved adjudications",
            blocker=(
                ""
                if release.ready
                else "No verified training-eligible labelset validation receipt exists."
            ),
            timestamp=timestamp,
            confidence=confidence,
        )
    )
    area_error = float(metric_row["ml_area_error_ratio"])
    legacy_feed = _truthy(metric_row["can_feed_decision_layer"])
    unsafe_legacy_gate = legacy_feed
    rows.append(
        _row(
            "query_model_safety_boundary",
            "phase_2",
            status="legacy_gate_rejected" if unsafe_legacy_gate else "blocked",
            severity="critical",
            observed=(
                f"legacy_can_feed={legacy_feed}; legacy_ml_area_error_ratio={area_error:.6f}"
            ),
            required="query_model_only=true and decision/FPPS/warning eligibility=false",
            blocker=(
                "Never reuse the legacy can_feed_decision_layer result for active learning."
                if unsafe_legacy_gate
                else (
                    "The legacy gate is hardened, but no query committee can be "
                    "trained until reviewed training labels exist."
                )
            ),
            timestamp=timestamp,
            confidence=confidence,
        )
    )
    rows.append(
        _row(
            "geographic_generalization",
            "phase_3",
            status="blocked",
            severity="critical",
            observed=(
                f"one weak-reference scene; sampled_cells={feature_row['sample_pixel_count']}; "
                f"weak_positive_cells={feature_row['reference_positive_pixel_count']}"
            ),
            required="multi-event development plus one untouched Thailand geographic test",
            blocker="More cells from the same scene do not establish event or basin transfer.",
            timestamp=timestamp,
            confidence=confidence,
        )
    )
    return pd.DataFrame(rows, columns=READINESS_COLUMNS)


def build_label_factory_readiness_summary(readiness: pd.DataFrame) -> str:
    """Render a concise Markdown readiness report without promoting blocked evidence."""

    _require_columns(readiness, READINESS_COLUMNS, "readiness table")
    blocked = readiness[readiness["status"].astype(str).isin({"blocked", "legacy_gate_rejected"})]
    lines = [
        "# Flood-label factory readiness",
        "",
        "Status: engineering foundation only; human and independent-data gates remain explicit.",
        "",
        "## Checks",
        "",
        "| Check | Phase | Status | Severity | Blocker |",
        "| --- | --- | --- | --- | --- |",
    ]
    for row in readiness.to_dict(orient="records"):
        blocker = str(row["blocker"]).replace("|", "/") or "-"
        lines.append(
            f"| {row['check_id']} | {row['phase']} | {row['status']} | "
            f"{row['severity']} | {blocker} |"
        )
    lines.extend(
        [
            "",
            "## Decision",
            "",
            (
                f"The label factory is not training- or decision-ready. {len(blocked)} "
                "critical or legacy-safety checks remain blocked."
                if not blocked.empty
                else "All configured checks passed; separate model-promotion evidence is still required."
            ),
            "",
            "Query-model and annotation outputs remain non-operational, not field validation, "
            "not an official warning, and ineligible for FPPS.",
        ]
    )
    return "\n".join(lines) + "\n"


def write_label_factory_readiness_outputs(
    manual_reference_manifest: pd.DataFrame | str | Path,
    weak_feature_manifest: pd.DataFrame | str | Path,
    weak_ml_metrics: pd.DataFrame | str | Path,
    *,
    csv_output_path: str | Path,
    summary_output_path: str | Path,
    canonical_tile_manifest: pd.DataFrame | str | Path | None = None,
    canonical_query_manifest: pd.DataFrame | str | Path | None = None,
    event_manifest: pd.DataFrame | str | Path | None = None,
    source_asset_manifest: pd.DataFrame | str | Path | None = None,
    processing_alignment_receipt: ReceiptInput | None = None,
    supported_query_derivation: str | Path | None = None,
    governance_package: str | Path | None = None,
    allow_ungoverned_fixture: bool = False,
    grid_validation_receipt: str | Path | None = None,
    annotation_log: str | Path | None = None,
    agreement_evidence: str | Path | None = None,
    reviewer_calibration_receipt: str | Path | None = None,
    labelset_validation_receipt: str | Path | None = None,
    annotation_manifest: pd.DataFrame | str | Path | None = None,
    labelset_manifest: pd.DataFrame | str | Path | None = None,
) -> dict[str, Path]:
    """Write the readiness CSV and Markdown summary."""

    readiness = build_label_factory_readiness(
        manual_reference_manifest,
        weak_feature_manifest,
        weak_ml_metrics,
        canonical_tile_manifest=canonical_tile_manifest,
        canonical_query_manifest=canonical_query_manifest,
        event_manifest=event_manifest,
        source_asset_manifest=source_asset_manifest,
        processing_alignment_receipt=processing_alignment_receipt,
        supported_query_derivation=supported_query_derivation,
        governance_package=governance_package,
        allow_ungoverned_fixture=allow_ungoverned_fixture,
        grid_validation_receipt=grid_validation_receipt,
        annotation_log=annotation_log,
        agreement_evidence=agreement_evidence,
        reviewer_calibration_receipt=reviewer_calibration_receipt,
        labelset_validation_receipt=labelset_validation_receipt,
        annotation_manifest=annotation_manifest,
        labelset_manifest=labelset_manifest,
    )
    csv_path = Path(csv_output_path)
    summary_path = Path(summary_output_path)
    if csv_path.suffix.lower() != ".csv":
        raise LabelFactoryReadinessError("Readiness table output must be CSV.")
    if summary_path.suffix.lower() not in {".md", ".markdown"}:
        raise LabelFactoryReadinessError("Readiness summary output must be Markdown.")
    csv_path.parent.mkdir(parents=True, exist_ok=True)
    summary_path.parent.mkdir(parents=True, exist_ok=True)
    readiness.to_csv(csv_path, index=False)
    summary_path.write_text(
        build_label_factory_readiness_summary(readiness),
        encoding="utf-8",
    )
    return {"readiness": csv_path, "summary": summary_path}


def _row(
    check_id: str,
    phase: str,
    *,
    status: str,
    severity: str,
    observed: str,
    required: str,
    blocker: str,
    timestamp: str,
    confidence: str,
) -> dict[str, object]:
    return {
        "check_id": check_id,
        "phase": phase,
        "status": status,
        "severity": severity,
        "observed": observed,
        "required": required,
        "blocker": blocker,
        "source_timestamp": timestamp,
        "confidence_class": confidence or "low",
        "assumptions": (
            "Ready states require complete contracts re-run through their validators "
            "or exact self-hashed validation receipts; missing or malformed evidence "
            "remains blocked rather than inferred."
        ),
    }


def _coerce_required(source: pd.DataFrame | str | Path, label: str) -> pd.DataFrame:
    frame = _coerce_optional(source)
    if frame is None or frame.empty:
        raise LabelFactoryReadinessError(f"{label} must not be empty.")
    return frame


def _coerce_optional(
    source: pd.DataFrame | str | Path | None,
) -> pd.DataFrame | None:
    if source is None:
        return None
    if isinstance(source, pd.DataFrame):
        return source.copy().fillna("")
    path = Path(source)
    if not path.exists():
        return None
    return pd.read_csv(path, dtype=str).fillna("")


def _require_columns(
    frame: pd.DataFrame,
    required: tuple[str, ...],
    label: str,
) -> None:
    missing = sorted(set(required) - set(frame.columns))
    if missing:
        raise LabelFactoryReadinessError(
            f"{label} is missing columns: {', '.join(missing)}"
        )


def build_grid_validation_receipt(
    event_manifest: pd.DataFrame | str | Path,
    source_asset_manifest: pd.DataFrame | str | Path,
    processing_alignment_receipt: ReceiptInput,
    canonical_tile_manifest: pd.DataFrame | str | Path,
    canonical_query_manifest: pd.DataFrame | str | Path,
    *,
    validated_at_utc: datetime | None = None,
    governance_package: str | Path | None = None,
    allow_ungoverned_fixture: bool = False,
    supported_query_derivation: str | Path | None = None,
) -> dict[str, Any]:
    """Validate the complete canonical grid and return a self-hashed receipt.

    This is the only receipt producer accepted by readiness.  It runs both
    source-registry validation and deterministic grid-manifest reconstruction
    before hashing the normalized records.  The receipt is a compact validation
    result, not a substitute for the source manifests in an audit archive.
    """

    try:
        events = load_events(event_manifest)
        sources = load_source_assets(source_asset_manifest)
        validate_event_source_registry(events, sources)
        processing_receipt = validate_processing_alignment_receipt(
            processing_alignment_receipt,
            events,
            sources,
            governance_package=governance_package,
            allow_ungoverned_fixture=allow_ungoverned_fixture,
        )
        canonical = validate_grid_manifests(
            events,
            sources,
            canonical_tile_manifest,
            canonical_query_manifest,
            processing_receipt,
            governance_package=governance_package,
            allow_ungoverned_fixture=allow_ungoverned_fixture,
            supported_query_derivation=supported_query_derivation,
        )
    except (EventRegistryError, ProcessingAlignmentError, ManifestContractError) as exc:
        raise LabelFactoryReadinessError(str(exc)) from exc
    grid_hashes = tuple(
        sorted(set(canonical.tiles["grid_contract_sha256"].astype(str)))
    )
    if not grid_hashes or any(not _is_sha256(value) for value in grid_hashes):
        raise LabelFactoryReadinessError(
            "Validated canonical grid has no complete grid-contract hash."
        )
    validated_at = _as_utc(validated_at_utc or datetime.now(timezone.utc))
    if "supported_query_derivation_sha256" in canonical.query_regions.columns:
        derivation_hashes = set(
            canonical.query_regions["supported_query_derivation_sha256"].astype(str)
        )
        if len(derivation_hashes) != 1 or any(
            not _is_sha256(value) for value in derivation_hashes
        ):
            raise LabelFactoryReadinessError(
                "Validated allowlisted queries do not have one supported-query "
                "derivation SHA-256."
            )
        supported_derivation_hash = next(iter(derivation_hashes))
    else:
        supported_derivation_hash = ""
    if governance_package is None:
        governance_fields: dict[str, Any] = {
            "governance_package_id": "",
            "governance_package_manifest_sha256": "",
            "governance_package_seal_sha256": "",
            "governance_binding_status": "synthetic_fixture_only",
            "production_readiness_eligible": False,
        }
    else:
        try:
            governance_seal = validate_rights_clearance_package(governance_package)
        except RightsClearanceError as exc:
            raise LabelFactoryReadinessError(
                f"Governance clearance package validation failed: {exc}"
            ) from exc
        governance_fields = {
            "governance_package_id": str(governance_seal["package_id"]),
            "governance_package_manifest_sha256": str(
                governance_seal["package_manifest_sha256"]
            ),
            "governance_package_seal_sha256": str(governance_seal["seal_sha256"]),
            "governance_binding_status": "validated",
            "production_readiness_eligible": True,
        }
    payload: dict[str, Any] = {
        "artifact_schema": GRID_VALIDATION_RECEIPT_SCHEMA,
        "validator": GRID_VALIDATOR_ID,
        "validated_at_utc": validated_at.isoformat().replace("+00:00", "Z"),
        "event_registry_sha256": _frame_sha256(
            pd.DataFrame([record.as_manifest_row() for record in events])
        ),
        "source_registry_sha256": _frame_sha256(
            pd.DataFrame([record.as_manifest_row() for record in sources])
        ),
        **governance_fields,
        "processing_alignment_receipt_schema": PROCESSING_ALIGNMENT_RECEIPT_SCHEMA,
        "processing_alignment_receipt_sha256": processing_receipt["receipt_sha256"],
        "tile_manifest_sha256": _frame_sha256(canonical.tiles),
        "query_manifest_sha256": _frame_sha256(canonical.query_regions),
        "supported_query_derivation_sha256": supported_derivation_hash,
        "grid_contract_sha256s": list(grid_hashes),
        "event_count": len(events),
        "source_asset_count": len(sources),
        "tile_count": len(canonical.tiles),
        "query_count": len(canonical.query_regions),
        "query_model_only": True,
        "eligible_for_decision_layer": False,
        "eligible_for_fpps": False,
        "eligible_for_warning": False,
    }
    return {**payload, "receipt_sha256": _canonical_json_sha256(payload)}


def write_grid_validation_receipt(
    receipt: Mapping[str, Any], path: str | Path
) -> Path:
    """Verify and immutably write one canonical-grid validation receipt."""

    normalized = _verify_grid_validation_receipt_payload(receipt)
    target = Path(path)
    if target.suffix.lower() != ".json":
        raise LabelFactoryReadinessError(
            "Grid validation receipt output must use a .json suffix."
        )
    target.parent.mkdir(parents=True, exist_ok=True)
    try:
        with target.open("x", encoding="utf-8") as handle:
            json.dump(normalized, handle, ensure_ascii=True, sort_keys=True, indent=2)
            handle.write("\n")
    except FileExistsError as exc:
        raise LabelFactoryReadinessError(
            f"Grid validation receipt is immutable and already exists: {target}"
        ) from exc
    return target


def load_grid_validation_receipt(path: str | Path) -> dict[str, Any]:
    """Load and cryptographically verify one grid-validation receipt."""

    if isinstance(path, pd.DataFrame):
        raise LabelFactoryReadinessError(
            "Grid readiness requires a self-hashed JSON receipt, not a table."
        )
    source = Path(path)
    if source.suffix.lower() != ".json":
        raise LabelFactoryReadinessError(
            "Grid validation receipt input must be a .json file."
        )
    try:
        payload = json.loads(source.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise LabelFactoryReadinessError(
            f"Could not load grid validation receipt: {source}"
        ) from exc
    return _verify_grid_validation_receipt_payload(payload)


def validate_grid_validation_receipt_against_evidence(
    receipt_path: str | Path,
    event_manifest: pd.DataFrame | str | Path,
    source_asset_manifest: pd.DataFrame | str | Path,
    processing_alignment_receipt: ReceiptInput,
    canonical_tile_manifest: pd.DataFrame | str | Path,
    canonical_query_manifest: pd.DataFrame | str | Path,
    *,
    governance_package: str | Path | None = None,
    allow_ungoverned_fixture: bool = False,
    supported_query_derivation: str | Path | None = None,
) -> dict[str, Any]:
    """Rebuild a grid receipt from exact evidence and require byte semantics match.

    The validation timestamp is taken from the supplied self-hashed receipt so
    that deterministic reconstruction can compare the complete payload rather
    than only selected lineage fields.
    """

    supplied = load_grid_validation_receipt(receipt_path)
    rebuilt = build_grid_validation_receipt(
        event_manifest,
        source_asset_manifest,
        processing_alignment_receipt,
        canonical_tile_manifest,
        canonical_query_manifest,
        validated_at_utc=_parse_receipt_timestamp(supplied["validated_at_utc"]),
        governance_package=governance_package,
        allow_ungoverned_fixture=allow_ungoverned_fixture,
        supported_query_derivation=supported_query_derivation,
    )
    if rebuilt != supplied:
        raise LabelFactoryReadinessError(
            "Grid validation receipt does not exactly reproduce from the supplied "
            "governance, processing, tile, query, and allowlist evidence."
        )
    return supplied


def _canonical_grid_assessment(
    *,
    event_manifest: pd.DataFrame | str | Path | None,
    source_asset_manifest: pd.DataFrame | str | Path | None,
    processing_alignment_receipt: ReceiptInput | None,
    canonical_tile_manifest: pd.DataFrame | str | Path | None,
    canonical_query_manifest: pd.DataFrame | str | Path | None,
    grid_validation_receipt: str | Path | None,
    supported_query_derivation: str | Path | None,
    governance_package: str | Path | None,
    allow_ungoverned_fixture: bool,
) -> _EvidenceAssessment:
    full_sources = (
        event_manifest,
        source_asset_manifest,
        processing_alignment_receipt,
        canonical_tile_manifest,
        canonical_query_manifest,
    )
    supplied_count = sum(source is not None for source in full_sources)
    if grid_validation_receipt is not None and supplied_count:
        return _EvidenceAssessment(
            False,
            "validation_failed=ambiguous_grid_evidence; supply either one receipt "
            "or all five event/source/processing/tile/query inputs, not both",
        )
    if grid_validation_receipt is not None:
        if governance_package is None:
            return _EvidenceAssessment(
                False,
                "validation_failed=grid_validation_receipt; "
                "governance_package_required=true",
            )
        try:
            receipt = load_grid_validation_receipt(grid_validation_receipt)
            governance = _validate_grid_receipt_governance_binding(
                receipt,
                governance_package,
            )
        except (
            LabelFactoryReadinessError,
            RightsClearanceError,
            OSError,
            TypeError,
            ValueError,
        ) as exc:
            return _failed_assessment("grid_validation_receipt", exc)
        return _EvidenceAssessment(
            True,
            "validated_grid_receipt=true; "
            f"events={receipt['event_count']}; sources={receipt['source_asset_count']}; "
            f"tiles={receipt['tile_count']}; queries={receipt['query_count']}; "
            f"governance_package_id={governance['package_id']}; "
            f"governance_seal_sha256={governance['seal_sha256']}; "
            f"receipt_sha256={receipt['receipt_sha256']}",
        )
    if supplied_count == 0:
        return _EvidenceAssessment(
            False,
            "no validated grid receipt or complete event/source/processing/tile/query evidence",
        )
    if supplied_count != len(full_sources):
        return _EvidenceAssessment(
            False,
            "validation_failed=partial_grid_evidence; required=events,source_assets,"
            "processing_alignment_receipt,tiles,queries",
        )
    try:
        receipt = build_grid_validation_receipt(
            event_manifest,  # type: ignore[arg-type]
            source_asset_manifest,  # type: ignore[arg-type]
            processing_alignment_receipt,  # type: ignore[arg-type]
            canonical_tile_manifest,  # type: ignore[arg-type]
            canonical_query_manifest,  # type: ignore[arg-type]
            governance_package=governance_package,
            allow_ungoverned_fixture=allow_ungoverned_fixture,
            supported_query_derivation=supported_query_derivation,
        )
    except (
        EventRegistryError,
        ProcessingAlignmentError,
        ManifestContractError,
        LabelFactoryReadinessError,
        OSError,
        TypeError,
        ValueError,
    ) as exc:
        return _failed_assessment("complete_grid_contract", exc)
    return _EvidenceAssessment(
        True,
        "validated_complete_grid_contract=true; "
        f"events={receipt['event_count']}; sources={receipt['source_asset_count']}; "
        f"tiles={receipt['tile_count']}; queries={receipt['query_count']}; "
        f"validation_receipt_sha256={receipt['receipt_sha256']}",
    )


def _validate_grid_receipt_governance_binding(
    receipt: Mapping[str, Any],
    governance_package: str | Path,
) -> dict[str, Any]:
    """Bind a standalone grid receipt to one semantically valid rights package."""

    if (
        receipt["governance_binding_status"] != "validated"
        or receipt["production_readiness_eligible"] is not True
    ):
        raise LabelFactoryReadinessError(
            "Grid receipt is synthetic-fixture-only and cannot satisfy production "
            "readiness."
        )
    root = Path(governance_package)
    seal = validate_rights_clearance_package(root)
    expected_governance = {
        "governance_package_id": str(seal["package_id"]),
        "governance_package_manifest_sha256": str(
            seal["package_manifest_sha256"]
        ),
        "governance_package_seal_sha256": str(seal["seal_sha256"]),
    }
    mismatches = [
        field
        for field, expected in expected_governance.items()
        if receipt[field] != expected
    ]
    if mismatches:
        raise LabelFactoryReadinessError(
            "Grid receipt governance identity does not match the supplied package: "
            + ", ".join(mismatches)
            + "."
        )
    events = load_events(root / "events.csv")
    sources = load_source_assets(root / "source_assets.csv")
    event_hash = _frame_sha256(
        pd.DataFrame([record.as_manifest_row() for record in events])
    )
    source_hash = _frame_sha256(
        pd.DataFrame([record.as_manifest_row() for record in sources])
    )
    if receipt["event_registry_sha256"] != event_hash:
        raise LabelFactoryReadinessError(
            "Grid receipt event registry does not match the governance package."
        )
    if receipt["source_registry_sha256"] != source_hash:
        raise LabelFactoryReadinessError(
            "Grid receipt source registry does not match the governance package."
        )
    return seal


def _double_review_assessment(
    annotation_log: pd.DataFrame | str | Path | None,
    agreement_evidence: str | Path | None,
) -> _EvidenceAssessment:
    if annotation_log is None and agreement_evidence is None:
        return _EvidenceAssessment(
            False,
            "no hash-chained annotation log or agreement evidence",
        )
    if annotation_log is None or agreement_evidence is None:
        return _EvidenceAssessment(
            False,
            "validation_failed=partial_double_review_evidence; required=annotation_log,agreement_evidence",
        )
    if isinstance(annotation_log, pd.DataFrame):
        return _EvidenceAssessment(
            False,
            "validation_failed=annotation_log; tabular reviewer rows are not a verified hash chain",
        )
    try:
        records = load_annotation_log(annotation_log)
        if not records:
            raise LabelFactoryReadinessError(
                "annotation log is missing or contains no locked records"
            )
        evidence = load_json_object(
            agreement_evidence,
            label="reviewer agreement evidence",
        )
        if evidence.get("artifact_schema") != AGREEMENT_EVIDENCE_SCHEMA:
            raise LabelFactoryReadinessError(
                f"agreement evidence must use {AGREEMENT_EVIDENCE_SCHEMA}"
            )
        reviewer_a_id = _required_text(
            evidence.get("reviewer_a_id"), "agreement reviewer_a_id"
        )
        reviewer_b_id = _required_text(
            evidence.get("reviewer_b_id"), "agreement reviewer_b_id"
        )
        pairs = pair_locked_annotations(
            records,
            reviewer_a_id=reviewer_a_id,
            reviewer_b_id=reviewer_b_id,
        )
        for pair in pairs:
            stages = {pair.reviewer_a.review_stage, pair.reviewer_b.review_stage}
            if stages != {ReviewStage.PRIMARY, ReviewStage.SECONDARY}:
                raise LabelFactoryReadinessError(
                    f"query {pair.query_region_id} does not contain one primary and one secondary review"
                )
        grid_hashes = {
            record.grid_contract_sha256
            for pair in pairs
            for record in (pair.reviewer_a, pair.reviewer_b)
        }
        if len(grid_hashes) != 1 or None in grid_hashes:
            raise LabelFactoryReadinessError(
                "review pairs do not share one complete grid-contract hash"
            )
        _require_agreement_gates(
            evidence,
            pairs=pairs,
            grid_contract_sha256=str(next(iter(grid_hashes))),
        )
        expected_hashes = {
            record.annotation_id: annotation_content_sha256(record)
            for pair in pairs
            for record in (pair.reviewer_a, pair.reviewer_b)
        }
        if evidence.get("annotation_sha256_by_id") != expected_hashes:
            raise LabelFactoryReadinessError(
                "agreement annotation hashes do not match exact latest locked reviews"
            )
    except (
        AdjudicationError,
        AnnotationValidationError,
        LabelFactoryReadinessError,
        ReviewWorkflowError,
        OSError,
        TypeError,
        ValueError,
        KeyError,
    ) as exc:
        return _failed_assessment("double_review", exc)
    return _EvidenceAssessment(
        True,
        "validated_blind_pairs=true; "
        f"reviewer_a={reviewer_a_id}; reviewer_b={reviewer_b_id}; "
        f"paired_queries={len(pairs)}; locked_annotation_hashes={len(expected_hashes)}; "
        f"agreement_evidence_sha256={_canonical_json_sha256(evidence)}",
    )


def _reviewer_calibration_assessment(
    source: str | Path | None,
) -> _EvidenceAssessment:
    if source is None:
        return _EvidenceAssessment(
            False,
            "missing=reviewer_calibration_receipt",
        )
    path = Path(source)
    if not path.is_file() or path.suffix.lower() != ".json":
        return _EvidenceAssessment(
            False,
            "validation_failed=reviewer_calibration_receipt; expected self-hashed JSON receipt",
        )
    try:
        receipt = load_reviewer_calibration_receipt(path)
    except (ReviewerCalibrationError, OSError, TypeError, ValueError) as exc:
        return _failed_assessment("reviewer_calibration_receipt", exc)
    return _EvidenceAssessment(
        True,
        "validated_reviewer_calibration_receipt=true; "
        f"receipt_sha256={receipt.receipt_sha256}; "
        f"reviewers={len(receipt.reviewer_ids)}; "
        f"queries={len(receipt.query_region_ids)}; "
        "eligible_for_query_model_training=false; eligible_for_fpps=false",
    )


def _training_release_assessment(
    source: pd.DataFrame | str | Path | None,
) -> _EvidenceAssessment:
    if source is None:
        return _EvidenceAssessment(False, "no labelset validation receipt")
    if isinstance(source, pd.DataFrame):
        return _EvidenceAssessment(
            False,
            "validation_failed=labelset_validation_receipt; compact tabular release claims are not proof",
        )
    path = Path(source)
    if path.suffix.lower() != ".json":
        return _EvidenceAssessment(
            False,
            "validation_failed=labelset_validation_receipt; expected self-hashed JSON receipt, not CSV",
        )
    try:
        receipt = load_labelset_validation_receipt(path)
    except (ReviewWorkflowError, OSError, TypeError, ValueError) as exc:
        return _failed_assessment("labelset_validation_receipt", exc)
    return _EvidenceAssessment(
        True,
        "validated_training_release=true; "
        f"labelset_id={receipt.labelset_id}; reviewed_queries={len(receipt.query_region_ids)}; "
        f"receipt_sha256={receipt.receipt_sha256}",
    )


def _select_aliased_evidence(
    *,
    preferred: Any,
    legacy: Any,
    preferred_name: str,
    legacy_name: str,
) -> tuple[Any, str | None]:
    if preferred is not None and legacy is not None:
        return None, (
            f"validation_failed=ambiguous_evidence; both {preferred_name} and "
            f"{legacy_name} were supplied"
        )
    return (preferred if preferred is not None else legacy), None


def _verify_grid_validation_receipt_payload(
    payload: Mapping[str, Any] | Any,
) -> dict[str, Any]:
    if not isinstance(payload, Mapping) or set(payload) != GRID_RECEIPT_KEYS:
        raise LabelFactoryReadinessError(
            "Grid validation receipt has unexpected or missing fields."
        )
    normalized = dict(payload)
    if normalized["artifact_schema"] != GRID_VALIDATION_RECEIPT_SCHEMA:
        raise LabelFactoryReadinessError("Unsupported grid validation receipt schema.")
    if normalized["validator"] != GRID_VALIDATOR_ID:
        raise LabelFactoryReadinessError("Unsupported grid validation receipt validator.")
    _parse_receipt_timestamp(normalized["validated_at_utc"])
    for field_name in (
        "event_registry_sha256",
        "source_registry_sha256",
        "processing_alignment_receipt_sha256",
        "tile_manifest_sha256",
        "query_manifest_sha256",
        "receipt_sha256",
    ):
        if not _is_sha256(normalized[field_name]):
            raise LabelFactoryReadinessError(
                f"Grid validation receipt {field_name} must be a SHA-256."
            )
    supported_derivation_hash = normalized[
        "supported_query_derivation_sha256"
    ]
    if supported_derivation_hash != "" and not _is_sha256(
        supported_derivation_hash
    ):
        raise LabelFactoryReadinessError(
            "Grid validation receipt supported_query_derivation_sha256 must be "
            "blank or a SHA-256."
        )
    binding_status = normalized["governance_binding_status"]
    production_eligible = normalized["production_readiness_eligible"]
    if binding_status == "validated":
        if (
            not isinstance(normalized["governance_package_id"], str)
            or not normalized["governance_package_id"].strip()
            or not _is_sha256(normalized["governance_package_manifest_sha256"])
            or not _is_sha256(normalized["governance_package_seal_sha256"])
            or production_eligible is not True
        ):
            raise LabelFactoryReadinessError(
                "Validated grid governance fields are incomplete or unsafe."
            )
    elif binding_status == "synthetic_fixture_only":
        if (
            normalized["governance_package_id"] != ""
            or normalized["governance_package_manifest_sha256"] != ""
            or normalized["governance_package_seal_sha256"] != ""
            or production_eligible is not False
        ):
            raise LabelFactoryReadinessError(
                "Synthetic grid receipts must have empty governance identity and be "
                "ineligible for production readiness."
            )
    else:
        raise LabelFactoryReadinessError(
            "Grid validation receipt has an unsupported governance binding status."
        )
    if normalized["processing_alignment_receipt_schema"] != PROCESSING_ALIGNMENT_RECEIPT_SCHEMA:
        raise LabelFactoryReadinessError(
            "Grid validation receipt has an unsupported processing receipt schema."
        )
    grid_hashes = normalized["grid_contract_sha256s"]
    if (
        not isinstance(grid_hashes, list)
        or not grid_hashes
        or grid_hashes != sorted(set(grid_hashes))
        or any(not _is_sha256(value) for value in grid_hashes)
    ):
        raise LabelFactoryReadinessError(
            "Grid validation receipt must contain sorted unique grid-contract hashes."
        )
    for field_name in (
        "event_count",
        "source_asset_count",
        "tile_count",
        "query_count",
    ):
        value = normalized[field_name]
        if isinstance(value, bool) or not isinstance(value, int) or value <= 0:
            raise LabelFactoryReadinessError(
                f"Grid validation receipt {field_name} must be a positive integer."
            )
    expected_safety = {
        "query_model_only": True,
        "eligible_for_decision_layer": False,
        "eligible_for_fpps": False,
        "eligible_for_warning": False,
    }
    if any(normalized[field] is not expected for field, expected in expected_safety.items()):
        raise LabelFactoryReadinessError(
            "Grid validation receipt contains unsafe or non-boolean safety flags."
        )
    unsigned = {key: value for key, value in normalized.items() if key != "receipt_sha256"}
    if _canonical_json_sha256(unsigned) != normalized["receipt_sha256"]:
        raise LabelFactoryReadinessError(
            "Grid validation receipt self-hash mismatch."
        )
    return normalized


def _frame_sha256(frame: pd.DataFrame) -> str:
    """Hash a deterministic CSV representation of already normalized records."""

    encoded = frame.to_csv(index=False, lineterminator="\n").encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def _canonical_json_sha256(value: Mapping[str, Any] | Sequence[Any]) -> str:
    encoded = json.dumps(
        value,
        ensure_ascii=True,
        sort_keys=True,
        separators=(",", ":"),
        allow_nan=False,
    ).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def _is_sha256(value: object) -> bool:
    if not isinstance(value, str) or len(value) != 64:
        return False
    return all(character in "0123456789abcdef" for character in value.lower())


def _as_utc(value: datetime) -> datetime:
    if not isinstance(value, datetime) or value.tzinfo is None:
        raise LabelFactoryReadinessError(
            "validated_at_utc must be a timezone-aware datetime."
        )
    return value.astimezone(timezone.utc).replace(microsecond=0)


def _parse_receipt_timestamp(value: object) -> datetime:
    if not isinstance(value, str) or not value.endswith("Z"):
        raise LabelFactoryReadinessError(
            "Grid validation receipt validated_at_utc must be explicit UTC."
        )
    try:
        parsed = datetime.fromisoformat(value[:-1] + "+00:00")
    except ValueError as exc:
        raise LabelFactoryReadinessError(
            "Grid validation receipt validated_at_utc is invalid."
        ) from exc
    return _as_utc(parsed)


def _required_text(value: object, field_name: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise LabelFactoryReadinessError(f"{field_name} must not be blank.")
    return value.strip()


def _failed_assessment(label: str, exc: BaseException) -> _EvidenceAssessment:
    detail = " ".join(str(exc).split()) or exc.__class__.__name__
    return _EvidenceAssessment(False, f"validation_failed={label}; detail={detail}")


def _truthy(value: object) -> bool:
    if isinstance(value, bool):
        return value
    return str(value).strip().lower() in {"true", "1", "yes", "eligible", "allowed"}
