import type { FinalsAnalysis, FinalsIntervention, FinalsRoute } from "@floodguard/contracts";

/** Open synthetic test data only; no fixture is exported into evidence packages. */
export function finalsAnalysisFixture(): FinalsAnalysis {
  const intervention: FinalsIntervention = { id: "add_destination-1", kind: "add_destination", target_id: "n3", target_label: "Synthetic site", selection_method: "Synthetic baseline-demand test.", gaining_15_min_access: 5, losing_15_min_access: 0, gaining_30_min_access: 10, losing_30_min_access: 0, gaining_60_min_access: 10, losing_60_min_access: 0, slower_population: 0, faster_population: 20, newly_reachable_population: 10, newly_unreachable_population: 0, comparable_population: 70, mean_travel_time_delta_minutes: -2, p90_delta_minutes: 0, max_delta_minutes: 0, net_person_minutes: -140 };
  const route: FinalsRoute = { status: "available", reason: "Synthetic route only.", destination_id: "hospital-1", destination_name: "Synthetic hospital", total_minutes: 12, network_minutes: 10, connector_minutes: 2, distance_m: 1000, edge_ids: ["edge-1"], coordinates: [[99.88,20.42],[99.89,20.42]], connectors: [[[99.88,20.421],[99.88,20.42]],[[99.89,20.42],[99.89,20.421]]] };
  return {
    schema_version: "1.0", generated_at: "2026-09-21T00:00:00Z", status: "scenario_only", question: "Synthetic conditional access question.", primary_service: "hospital", analysis_sha256: "a".repeat(64),
    scope: { jurisdiction: "Synthetic Thailand-side selection.", population_year: 2020, boundary_reference_date: "2022-01-22", osm_retrieved_at: "2026-09-21", study_population: 110, in_scope_population: 100, excluded_population: 10 },
    timeline: [{ id: "synthetic", title: "Synthetic candidate", start: "2024-09-15", end: "2024-09-15", role: "candidate", source_url: "https://example.org/candidate", limitations: ["Synthetic test only."] }],
    services: [
      { id: "hospital", status: "available", facilities: 1, reason: "Synthetic candidate.", variants: (["walking", "modelled_vehicle"] as const).flatMap((travel_mode) => [.75, 1, 1.25].map((speed_factor) => ({ id: `hospital-${travel_mode}-${speed_factor}`, travel_mode, speed_factor, context_sha256: "b".repeat(64), baseline: { modelled_population: 100, unknown_access_population: 10, connected_without_route_population: 20, within_15_minutes_population: 30, within_30_minutes_population: 50, within_60_minutes_population: 70, median_minutes: 20, p90_minutes: 40, max_minutes: 50 }, interventions: [{ ...intervention }] }))) },
      ...(["primary_care", "pharmacy", "shelter"] as const).map((id) => ({ id, status: "unavailable" as const, facilities: 0, reason: "No eligible synthetic destination.", variants: [] })),
    ],
    facility_review: [{ id: "hospital-1", name: "Synthetic hospital", service_type: "hospital", geometry_role: "point", eligible: true, event_availability: "unknown", actual_capacity: null, source_url: "https://example.org/hospital" }],
    routes: { status: "available", origins: [{ id: "origin-1", name: "Synthetic public square", longitude: 99.88, latitude: 20.421, source_url: "https://example.org/square", geometry_role: "point", location_status: "entrance_unverified" }], comparisons: [{ id: "origin-1-hospital-walking-close", origin_id: "origin-1", service_type: "hospital", travel_mode: "walking", scenario_kind: "close_edge", changed_ids: ["edge-1"], selection_method: "Synthetic path-based selection.", context_sha256: "b".repeat(64), baseline: route, after: { ...route, total_minutes: 17, network_minutes: 15, edge_ids: ["edge-2","edge-3"], coordinates: [[99.88,20.42],[99.885,20.43],[99.89,20.42]] }, delta_minutes: 5 }], limitations: ["Synthetic routes are not safe-travel instructions."] },
    topology_review: { reviewed_candidates: 2, accepted_connections: 0, summary: "Synthetic review queue; no accepted correction." },
    focus_briefs: [{ id: "unit-1", name: "Synthetic unit", name_th: "พื้นที่ทดสอบ", unit_coverage_fraction: .5, modelled_population: 100, priority: "verification", service_type: "hospital", travel_mode: "walking", main_drivers: ["Synthetic access gap."], useful_intervention: "Review the synthetic site.", uncertainty: ["No event availability."] }],
    capacity: { status: "scenario_only", site_id: "hypothetical-n3", linked_access_intervention_id: "add_destination-1", linked_service: "hospital", linked_variant_id: "hospital-walking-1", demand_basis: "residential_participation", actual_evacuation_demand: null, actual_available_capacity: null, experiments: [{ participation_fraction: .1, places: 100, assumed_demand: 10, assigned: 8, capacity_limited: 0, unreachable: 1, coverage_excluded: 1 }], assumptions: ["Synthetic residential participation only."] },
    limitations: ["Synthetic test fixture only."],
  };
}
