const SOURCE_COMMIT = "2e5a099ee075532e27236067810699ce6996c5c4";
const SOURCE_ROOT = `https://github.com/TUPRAM/flood-guard/blob/${SOURCE_COMMIT}`;

/** Fixed historical example reproduced from the committed r2 study, independent of the active replay. */
export const POLICY_EVIDENCE = {
  title: "Latest reproduced priority study",
  context: "Mae Sai historical reconstruction · assumed peak · reported 2024 shelter set",
  generatedAt: null,
  sourceCommittedAt: "2026-09-28T07:45:21Z",
  reproducedOn: "2026-09-29",
  sourceCommit: SOURCE_COMMIT,
  sourceArtifact: "apps/web/public/studies/mae-sai-2024-timeline/r2/timeline.json",
  sourceSha256: "5e2cea385ac7fe53952976e4d6cc75aed54b997b62d55aa7652fdcf83964eb6b",
  sourceUrl: `${SOURCE_ROOT}/apps/web/public/studies/mae-sai-2024-timeline/r2/timeline.json`,
  methodUrl: `${SOURCE_ROOT}/apps/web/src/lib/replay-fpps.ts`,
  scoringUrl: `${SOURCE_ROOT}/apps/web/src/lib/fpps.ts`,
  playbookUrl: `${SOURCE_ROOT}/apps/web/src/lib/action-playbook.ts`,
  revision: "r2",
  schemaVersion: 1,
  confidence: "low",
  confidenceReason: "Terrain-model reconstruction with illustrative stages; spatial agreement with late-recession radar is weak.",
  eventStart: "2024-09-09",
  eventEnd: "2024-09-19",
  sourceTimestamp: "2024-09-05T03:58:19Z/2024-09-15T23:16:01Z",
  scenario: {
    timestamp: "2024-09-12T12:00:00+07:00",
    label: "12 September 2024, 12:00 ICT",
    assumedStageMetres: 3.5,
    shelterSet: "reported_2024",
    shelterLabel: "Shelters reported in use in September 2024",
    population: "WorldPop 2020 modelled residents",
    anchorVersion: "replay_fpps_anchor_v1",
  },
  stats: [
    { label: "Mae Sai", value: "89.34", unit: "scenario FPPS", detail: "Class E · low confidence" },
    { label: "Si Mueang Chum", value: "85.98", unit: "scenario FPPS", detail: "Class E · low confidence" },
    { label: "Ban Dai", value: "81.14", unit: "scenario FPPS", detail: "Class E · low confidence" },
  ],
  rankings: [
    { id: "TH570901", name: "Mae Sai", nameTh: "แม่สาย", score: 89.34, actionClass: "E" },
    { id: "TH570905", name: "Si Mueang Chum", nameTh: "ศรีเมืองชุม", score: 85.98, actionClass: "E" },
    { id: "TH570908", name: "Ban Dai", nameTh: "บ้านด้าย", score: 81.14, actionClass: "E" },
    { id: "TH570903", name: "Ko Chang", nameTh: "เกาะช้าง", score: 76.38, actionClass: "E" },
    { id: "TH570904", name: "Pong Pha", nameTh: "โป่งผา", score: 66.13, actionClass: "E" },
    { id: "TH570909", name: "Pong Ngam", nameTh: "โป่งงาม", score: 53.93, actionClass: "E" },
    { id: "TH570902", name: "Huai Khrai", nameTh: "ห้วยไคร้", score: 34.09, actionClass: "E" },
    { id: "TH570906", name: "Wiang Phang Kham", nameTh: "เวียงพางคำ", score: 31.27, actionClass: "E" },
  ],
  weights: { flood: 0.3, exposure: 0.25, access: 0.2, roads: 0.15, context: 0.1 },
  anchors: {
    floodAreaShare: 0.25,
    exposedPopulationShare: 0.25,
    exposedPeople: 5000,
    disruptedWeightedRoadShare: 0.5,
    terrainRemotenessPopulationShare: 0.25,
  },
  officialWarning: false,
  canFeedDecisionLayer: false,
  acceptedFpps: null,
  acceptedActionClass: null,
  assumptions: [
    "Scenario FPPS is a priority index, not a flood probability or an official priority list.",
    "The first component is a normalized reconstructed inundated-area proxy; a full component score does not mean certain flooding.",
    "Access assumes a dry shelter within 2 km on modeled passable roads; site operation and safe travel are unverified.",
    "The access calculation is not a capacity-constrained shelter allocation.",
    "Vulnerability is a terrain/remoteness proxy, not a demographic or social-vulnerability assessment.",
    "Every assigned class remains E because confidence is low. Confirming water alone does not authorize escalation.",
  ],
  verification: {
    scoreReproduction: "Recomputed all eight rows from the exact committed TypeScript methods and original r2 Git asset bytes.",
    sourceSelection: "The later r3 visualization checkpoint does not contain the completed FPPS feature. Work in the separate integrated checkout remains in progress and is excluded.",
    generationTimestamp: "The source manifest does not record a generation time; the commit date is recorded separately.",
    scientificValidation: "Not established",
    operationalAcceptance: "Not established",
  },
} as const;
